# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('constellation_base', '0002_remove_sidebar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGroupACL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Supplemental Group ACL',
                'verbose_name_plural': 'Supplemental Group ACLs',
            },
        ),
    ]
